# Where you store your data
# -------------------------
# your data must be organized this way:
#|- /[path_to_data]
#     |- samples.csv
#     |- /[your_sample_1]
#          |- r1.fastq
#          |- r2.fastq
#          |- ref.fasta
#          |- library.csv
#     |- /[your_sample_2]
#          |- ...
#     |- /[your_sample_3]
#          |- ...
#     |- ...

path_to_data: /Users/ymdt/src/dreem/test/resources/  

# it's not recommanded to change this
files_per_sample:
  - r1.fastq
  - r2.fastq
  - ref.fasta
  - library.csv

# The samples that you want to process today
# ------------------------------------------
# These names must correspond to
#     - the sample column in samples.csv
#     - the name of your data folders
#
# Nota bene: obviously, the name of your data folders must match the sample column of samples.csv

samples:
  - case_1
 # - case_2

# The arguments to pass direcly to DREEM
# --------------------------------------
# More information about hese arguments here: https://github.com/jyesselm/dreem#run

dreem_args:
    overwrite: False     # Re-compute the bitvector if it already exists. Takes more time.
   # RNAstructure_path:  # where RNAstructure/exe is located on your computer. Remove if you don't want to run RNAstructure
    temperature: False  # Use samples.csv col 'temperature_k' as an input for RNAstructure
    bootstrap: True     # Run bootstrap

# Print more information during run time
verbose: True

# There's a bunch of folders in output/. This option creates a folder such that:
# /mh_only
#   |- your_sample_1
#       |- mh.p
#   |- your_sample_2
#       |- mh.p
#   ...
mut_hist_only_folder: True
